name: CI-Secure
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r app/requirements.txt

      - name: Build Docker image
        run: docker build -t devsecops-demo:${{ github.sha }} .
